spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board_spring
    username: root
    password: 1234
  jpa:
    databases: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  logging:
#    로그파일 경로와 파일명 지정
    file:
      name: logs/app.log
    # trace < debug < info < error 순서의 로그 레벨을 가짐
    # info로  설정시 trace, debug 로그는 출력되지 않음
    level:
      root: error